[package]
name = "dioscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id_tree = "1.8.0"
nom = { version = "7" }

thiserror = "1.0.40"
