[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dsx = { path = "../dsx" }
dioxus = "0.4.3"
dioxus-web = "0.4.3"
dioxus-router = "0.4.3"
js-sys = "0.3"
indoc = "2.0.4"
