[package]
name = "dioscript-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]

dioscript-parser = { path = "../parser" }
dyn-clone = "1.0.11"

uuid = { version = "1.6.1", default-features = false, features = ["v4", "js"] }
thiserror = "1.0.40"
