[package]
name = "dsx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioscript-parser = { path = "../parser" }
dioscript-runtime = { path = "../runtime" }
dioxus = "0.3.2"
dioxus-desktop = "0.3.0"
