[package]
name = "ds"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"

clap = { version = "4.3.1", features = ["derive"] }

dioscript-parser = { path = "../parser" }
dioscript-runtime = { path = "../runtime" }

colored = "2.0.0"
opener = "0.6.1"
rustyline = "11.0.0"
